name: 'generate and publish GRPC docker caches'

on:
- workflow_dispatch

concurrency:
  group: ci-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true

jobs:
  generate_caches:
    # secrets:
    #   dockerUsername: ${{ secrets.DOCKERHUB_USERNAME }}
    #   dockerPassword: ${{ secrets.DOCKERHUB_PASSWORD }}
    #   quayUsername: ${{ secrets.LOCALAI_REGISTRY_USERNAME }}
    #   quayPassword: ${{ secrets.LOCALAI_REGISTRY_PASSWORD }}
    strategy:
      matrix:
        include:
          - base-image: ubuntu:22.04
            runs-on: 'ubuntu-latest'
            platforms: 'linux/amd64'
            makeflags: "--jobs=3 --output-sync=target"
            tag: grpc-ubuntu-22-04-linux-amd64
          - base-image: rocm/dev-ubuntu-22.04:6.0-complete
            runs-on: 'ubuntu-latest'
            platforms: 'linux/amd64'
            makeflags: "--jobs=3 --output-sync=target"
            tag: grpc-rocm-6-0-ubuntu-22-04-linux-amd64
          - base-image: intel/oneapi-basekit:2024.0.1-devel-ubuntu22.04
            runs-on: 'ubuntu-latest'
            platforms: 'linux/amd64'
            makeflags: "--jobs=3 --output-sync=target"
            tag: grpc-oneapi-2024-0-1-ubuntu-22-04-linux-amd64
    runs-on: ${{matrix.runs-on}}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerUsername }}
          password: ${{ secrets.dockerPassword }}

      # - name: Login to DockerHub
      #   uses: docker/login-action@v3
      #   with:
      #     registry: quay.io
      #     username: ${{ secrets.quayUsername }}
      #     password: ${{ secrets.quayPassword }}

      - name: Cache GRPC
        uses: docker/build-push-action@v5
        with:
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            MAKEFLAGS=${{ matrix.makeflags }}
            GRPC_VERSION=v1.58.0
          context: .
          file: ./Dockerfile
          cache-to: type=registry,ignore-error=true
          target: grpc
          platforms: ${{ matrix.platforms }}
          push: false
          tags: ${{matrix.tag}}